/**
 * 路由路径常量定义。
 */
import { AppRoutePath } from './RouteTypes'

export const HOME_PATH: AppRoutePath = '/home'
export const TRAIN_PATH: AppRoutePath = '/train'
export const RECORD_PATH: AppRoutePath = '/record'
export const PROFILE_PATH: AppRoutePath = '/profile'
export const LAUNCH_PATH: AppRoutePath = '/launch'
export const LOGIN_SMS_PATH: AppRoutePath = '/login-sms'
export const LOGIN_PASSWORD_PATH: AppRoutePath = '/login-password'
export const REGISTER_PATH: AppRoutePath = '/register'
export const PROFILE_FAVORITES_PATH: AppRoutePath = '/profile/favorites'
export const PROFILE_ACCOUNT_PATH: AppRoutePath = '/profile/account'
export const PROFILE_SECURITY_PATH: AppRoutePath = '/profile/security'
export const PROFILE_PASSWORD_PATH: AppRoutePath = '/profile/password'
export const PROFILE_FEEDBACK_PATH: AppRoutePath = '/profile/feedback'
export const PROFILE_ABOUT_PATH: AppRoutePath = '/profile/about'
export const COURSE_DETAIL_BASE_PATH: AppRoutePath = '/course'
export const TRAIN_SESSION_BASE_PATH: AppRoutePath = '/train-session'
export const COURSE_DETAIL_PATH: AppRoutePath = '/course/:courseCode'
export const TRAIN_SESSION_PATH: AppRoutePath = '/train-session/:courseCode/:itemCode'
export const TRAIN_SESSION_COURSE_PATH: AppRoutePath = '/train-session/:courseCode'
